# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcEnrichmentScoreCPP <- function(Set, Eso, exponent) {
    .Call('_DeepCC_calcEnrichmentScoreCPP', PACKAGE = 'DeepCC', Set, Eso, exponent)
}

calcEnrichmentScoreBatchCPP <- function(expr, setStarts, setMembers, nthreads = 1L, exponent = 1.0) {
    .Call('_DeepCC_calcEnrichmentScoreBatchCPP', PACKAGE = 'DeepCC', expr, setStarts, setMembers, nthreads, exponent)
}

